export const GET_INITIAL_POCKETS = 'GET_INITIAL_POCKETS';
export const GET_EXCHANGE_RATES = 'GET_EXCHANGE_RATES';
export const GET_EXCHANGE_RATES_START = 'GET_EXCHANGE_RATES_START';
export const GET_EXCHANGE_RATES_SUCCESS = 'GET_EXCHANGE_RATES_SUCCESS';
